### PR TITLE
Update to aiida 0.12.2

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Comment by zhubonan** [comment]
Could you please also assign an tag to the newly built the docker image? something like 0.12.2 perhaps. Thanks.

**Comment by ltalirz** [comment]
@zhubonan Done, building now - thanks for the hint!

**Comment by zhubonan** [comment]
@ltalirz  hmm, it seems that the 0.12.2 taged image is actually 0.11.2, see here: https://hub.docker.com/r/aiidateam/aiida_core_base/builds/bruqj3ymjrblda8zbnc7jbh/

**Comment by ltalirz** [comment]
sorry about this - I hadn't realized the PR was to `develop`.
Should be fixed now, v0.12.2 is rebuilding
https://hub.docker.com/r/aiidateam/aiida_core_base/builds/

**Comment by ltalirz** [comment]
> some dependecies for the pgtest are missing, such as the pg_ctl binary

Looking at [quantum mobile](https://github.com/marvel-nccr/quantum-mobile/releases) which also runs ubuntu 18.04, I guess it is installed but we need to add `/usr/lib/postgresql/10/bin/pg_ctl` to the `PATH`.

> and also locate used for finding it.

That would be `sudo apt install mlocate`

Since you are working on this - would you mind adding a PR?

**Comment by zhubonan** [comment]
Sure I will add a PR soon. 
I find that `pg_ctl` is in package `postgresql-10` which is not installed as dockerfile only instruct to install `postgresql-client-10` and `postgresql-server-dev-10`.

**Pull request merged**
